[package]
name = "wlrs"
version = "0.1.1"
edition = "2021"
description = "/ˈwɑːl.rəs/ - Wallpaper management library"
license = "MIT"
repository = "https://github.com/unixpariah/wlrs"
readme = "README.md"
authors = ["unixpariah"]

[dependencies]
anyhow = "1.0.79"
image = "0.24.8"
smithay-client-toolkit = "0.16.1"
